import { useEffect, useRef, useState } from "react";
import { api } from "../api";

// The timer sound library, managed from Settings.
//
// Built-ins are synthesised on the server rather than shipped as files
// (see sound_service) and cannot be deleted -- every timer's warning and
// finish sound is chosen from this list, and a list the household can
// empty is a timer that goes off in silence. Uploads sit beside them and
// can be removed freely.
export default function SoundLibraryPanel() {
  const [sounds, setSounds] = useState([]);
  const [name, setName] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const fileRef = useRef(null);

  async function refresh() {
    try {
      setSounds(await api.get("/sounds"));
    } catch (e) {
      setError(e.message);
    }
  }

  useEffect(() => {
    refresh();
  }, []);

  async function upload(event) {
    event.preventDefault();
    setError(null);
    const file = fileRef.current?.files?.[0];
    if (!file) {
      setError("Choose an audio file first.");
      return;
    }
    const body = new FormData();
    body.append("name", name.trim() || file.name.replace(/\.[^.]+$/, ""));
    body.append("file", file);
    setBusy(true);
    try {
      await api.post("/sounds", body);
      setName("");
      if (fileRef.current) fileRef.current.value = "";
      await refresh();
    } catch (e) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  async function remove(sound) {
    if (!window.confirm(`Delete the sound "${sound.name}"? Timers set to use it will fall back to a built-in chime.`)) {
      return;
    }
    setError(null);
    try {
      await api.del(`/sounds/${sound.id}`);
      await refresh();
    } catch (e) {
      setError(e.message);
    }
  }

  return (
    <div className="sound-library">
      <p className="hint">
        Used for cooking-timer warning and finish sounds. The five built-ins are generated by the app itself, so
        they survive a container rebuild and carry no licence of their own. Anything you upload lives on the same
        data volume and survives too.
      </p>

      <ul className="sound-list">
        {sounds.map((s) => (
          <li key={s.id} className="sound-row">
            <span className="sound-name">
              {s.name}
              {s.is_builtin && <span className="tag">built-in</span>}
              {s.missing_file && <span className="tag tag-warning">file missing</span>}
            </span>
            <audio controls preload="none" src={`/api/sounds/${s.id}/audio`}>
              <track kind="captions" />
            </audio>
            {!s.is_builtin && (
              <button type="button" className="btn-link btn-link-danger" onClick={() => remove(s)}>
                Delete
              </button>
            )}
          </li>
        ))}
      </ul>

      <form className="sound-upload" onSubmit={upload}>
        <label>
          Name (optional)
          <input value={name} onChange={(e) => setName(e.target.value)} placeholder="Kitchen bell" />
        </label>
        <label>
          Audio file
          <input ref={fileRef} type="file" accept="audio/*" />
        </label>
        <button type="submit" className="btn btn-secondary" disabled={busy}>
          {busy ? "Uploading..." : "Add sound"}
        </button>
      </form>
      {error && <p className="error-text">{error}</p>}
    </div>
  );
}
