"""add recipe variant parent link and label

Revision ID: 349c7fd3ed4c
Revises: 5ee4a7ad013b
Create Date: 2026-07-31 09:28:11.350327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349c7fd3ed4c'
down_revision: Union[str, None] = '5ee4a7ad013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite can't ALTER TABLE to add a foreign key constraint directly --
    # batch mode (copy-and-move) is required. Adjusted from the raw
    # autogenerated op.create_foreign_key(), which raises NotImplementedError
    # on this dialect.
    with op.batch_alter_table("recipes") as batch_op:
        batch_op.add_column(sa.Column("parent_recipe_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("variant_label", sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(
            "fk_recipes_parent_recipe_id_recipes", "recipes", ["parent_recipe_id"], ["id"]
        )


def downgrade() -> None:
    with op.batch_alter_table("recipes") as batch_op:
        batch_op.drop_constraint("fk_recipes_parent_recipe_id_recipes", type_="foreignkey")
        batch_op.drop_column("variant_label")
        batch_op.drop_column("parent_recipe_id")
