"""add knowledge chunks table and indexed embed model

Revision ID: 5ee4a7ad013b
Revises: 5c07836d9339
Create Date: 2026-07-31 08:52:25.640360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee4a7ad013b'
down_revision: Union[str, None] = '5c07836d9339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_file_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_file_id'], ['knowledge_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_knowledge_file_id'), 'knowledge_chunks', ['knowledge_file_id'], unique=False)
    op.add_column('knowledge_files', sa.Column('indexed_embed_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_files', 'indexed_embed_model')
    op.drop_index(op.f('ix_knowledge_chunks_knowledge_file_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    # ### end Alembic commands ###
