"""add meal plan entry guidance and grocery item category

Revision ID: 67a6d7e5b6e5
Revises: 957de2f3c51d
Create Date: 2026-07-30 20:36:02.936589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a6d7e5b6e5'
down_revision: Union[str, None] = '957de2f3c51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list_items', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('meal_plan_entries', sa.Column('requested_tags', sa.JSON(), nullable=False))
    op.add_column('meal_plan_entries', sa.Column('is_indulgence', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plan_entries', 'is_indulgence')
    op.drop_column('meal_plan_entries', 'requested_tags')
    op.drop_column('grocery_list_items', 'category')
    # ### end Alembic commands ###
