"""add recipe source citation and tips fields

Revision ID: 957de2f3c51d
Revises: 5528780c5690
Create Date: 2026-07-30 20:18:41.635383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957de2f3c51d'
down_revision: Union[str, None] = '5528780c5690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('source_url', sa.String(length=1000), nullable=True))
    op.add_column('recipes', sa.Column('source_name', sa.String(length=200), nullable=True))
    op.add_column('recipes', sa.Column('source_author', sa.String(length=200), nullable=True))
    op.add_column('recipes', sa.Column('tips', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'tips')
    op.drop_column('recipes', 'source_author')
    op.drop_column('recipes', 'source_name')
    op.drop_column('recipes', 'source_url')
    # ### end Alembic commands ###
