"""add knowledge file content and active flag

Revision ID: a4a23dff4e5e
Revises: 67a6d7e5b6e5
Create Date: 2026-07-30 20:53:24.418765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a23dff4e5e'
down_revision: Union[str, None] = '67a6d7e5b6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_files', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('knowledge_files', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_files', 'is_active')
    op.drop_column('knowledge_files', 'content')
    # ### end Alembic commands ###
